# Generated by Django 5.2.13 on 2026-04-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Anúncio patrocinado'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_store_featured',
            field=models.BooleanField(default=False, help_text='Destaque para anúncios de loja'),
        ),
    ]
