# Generated by Copilot to extend PF/PJ profile data

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0006_alter_listing_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='commonprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='commonprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='state_registration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='responsible_cpf',
            field=models.CharField(
                blank=True,
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        message='CPF deve estar no formato 000.000.000-00.',
                        regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$',
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='commercial_cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='commercial_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='cpf',
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='CPF deve estar no formato 000.000.000-00.',
                        regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='cnpj',
            field=models.CharField(
                max_length=18,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='CNPJ deve estar no formato 00.000.000/0000-00.',
                        regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$',
                    )
                ],
            ),
        ),
    ]
