# Generated by Copilot to add trade negotiation models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0007_extend_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('negotiating', 'Em negociação'), ('approved', 'Aprovada'), ('rejected', 'Reprovada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('initial_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests_received', to='marketplace_app.user')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests', to='marketplace_app.listing')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests_created', to='marketplace_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='TradeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_messages_sent', to='marketplace_app.user')),
                ('trade_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace_app.traderequest')),
            ],
        ),
    ]
