# Generated by Copilot to support checkout and cart item actions

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0008_trade_request_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='desired_action',
            field=models.CharField(choices=[('buy', 'Compra'), ('trade', 'Troca')], default='buy', max_length=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de crédito'), ('debit_card', 'Cartão de débito'), ('bank_transfer', 'Transferência bancária')], max_length=20)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Retirada presencial'), ('seller_shipping', 'Frete do vendedor'), ('platform_shipping', 'Frete da plataforma'), ('to_agree', 'A combinar')], default='to_agree', max_length=20)),
                ('status', models.CharField(choices=[('pending_payment', 'Aguardando pagamento'), ('paid', 'Pago'), ('cancelled', 'Cancelado'), ('completed', 'Concluído')], default='pending_payment', max_length=20)),
                ('total_amount', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=255)),
                ('unit_price_snapshot', models.DecimalField(max_digits=10, decimal_places=2)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace_app.listing')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace_app.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='marketplace_app.user')),
            ],
        ),
    ]
