# Generated by Copilot to add payment transaction and delivery models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0009_cartitem_order_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mercado_pago', 'Mercado Pago')], default='mercado_pago', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado')], default='pending', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('preference_id', models.CharField(blank=True, max_length=255)),
                ('checkout_url', models.URLField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='marketplace_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pickup', 'Retirada presencial'), ('seller_shipping', 'Frete do vendedor'), ('platform_shipping', 'Frete da plataforma'), ('to_agree', 'A combinar')], default='to_agree', max_length=20)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carrier_name', models.CharField(blank=True, max_length=120)),
                ('tracking_code', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('preparing', 'Separando'), ('in_transit', 'Em trânsito'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='marketplace_app.order')),
            ],
        ),
    ]
