# Generated by Django 6.0.5 on 2026-05-29 01:38

import marketplace_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0013_tradedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonprofile',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[marketplace_app.models.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[marketplace_app.models.validate_cnpj]),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='responsible_cpf',
            field=models.CharField(blank=True, max_length=14, validators=[marketplace_app.models.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='tradedelivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tradeproposalimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
