# Generated by Django 6.0.5 on 2026-05-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0015_sync_category_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
